---
title: "Schedule"
toc: false
format:
  html:
    page-layout: full
---

Below is a breakdown of topics for each class day this semester. Assignments are also listed according to their due dates. The associated links take you to additional information relevant for that day or for that assignment. Each heading is also linked to a broader literature review for that topic, containing many more papers than we will cover in class. For those of you interested in learning more about a particular topic, this is a good place to start.
  

## Welcome to the class!

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  1    | 1/13   | Introductions                         | [{{< fa magnifying-glass  >}}](/schedule/0-0.html)       | 
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 1: [Health Insurance and Market Design](1-literature.qmd)

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  2    | 1/15   | Demand for Health Insurance           | [{{< fa magnifying-glass >}}](/schedule/1-0.html)        | 
|       | 1/16   | **Select Papers to Present**          | [{{< fa pen  >}}](/assignments/presentations.html)       |
|  3    | 1/20   | Welfare Effects of Health Insurance   | [{{< fa magnifying-glass >}}](/schedule/1-1.html)        |
|  4    | 1/22   | Adverse Selection                     | [{{< fa magnifying-glass >}}](/schedule/1-2.html)        |
|  5    | 1/27   | Competition and Market Structure      | [{{< fa magnifying-glass >}}](/schedule/1-3.html)        |
|  6    | 1/29   | Public Insurance Design               | [{{< fa magnifying-glass >}}](/schedule/1-4.html)        |
|       |        | **Select Empirical Exercise**         | [{{< fa pen  >}}](/assignments/empirical-exercises.html) |
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 2: [Physician Agency and Treatment Decisions](2-literature.qmd)

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  7    | 2/3    | Physician Agency                      | [{{< fa magnifying-glass >}}](/schedule/2-0.html)        |
|  8    | 2/5    | Financial Incentives                  | [{{< fa magnifying-glass >}}](/schedule/2-1.html)        |
|       |        | **Research Proposal 1 Due**           | [{{< fa pen  >}}](/assignments/research-proposals.html)  |
|  9    | 2/10   | Non-financial Incentives              | [{{< fa magnifying-glass >}}](/schedule/2-2.html)        |
|  10   | 2/12   | Agency in Organizations and Teams     | [{{< fa magnifying-glass >}}](/schedule/2-3.html)        |
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 3: [Physician Learning and Technology Adoption](3-literature.qmd)

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  11   | 2/17   | Learning under Uncertainty            | [{{< fa magnifying-glass >}}](/schedule/3-0.html)         |
|  12   | 2/19   | Skill Accumulation                    | [{{< fa magnifying-glass >}}](/schedule/3-1.html)         |
|  13   | 2/24   | Patient-Treatment Match Value         | [{{< fa magnifying-glass >}}](/schedule/3-2.html)         |
|  14   | 2/26   | Learning from Others                  | [{{< fa magnifying-glass >}}](/schedule/3-3.html)         |
|       |        | **Research Proposal 2 Due**           | [{{< fa pen  >}}](/assignments/research-proposals.html)   |
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 4: [Hospital Competition and Pricing](4-literature.qmd)

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  15   | 3/3    | Understanding Hospital Competition    | [{{< fa magnifying-glass >}}](/schedule/4-0.html)        |  
|  16   | 3/5    | Competition in Reduced Form           | [{{< fa magnifying-glass >}}](/schedule/4-1.html)        |  
|  17   | 3/17   | Bargaining and Hospital Pricing       | [{{< fa magnifying-glass >}}](/schedule/4-2.html)        | 
|       |        | **Excellence Blueprint Due**          | [{{< fa pen  >}}](/assignments/excellence-blueprint.html)   | 
|  18   | 3/19   | Cross-market Mergers                  | [{{< fa magnifying-glass >}}](/schedule/4-3.html)        |  
|  19   | 3/24   | Vertical Integration                  | [{{< fa magnifying-glass >}}](/schedule/4-4.html)        |  
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 5: [Information Disclosure and Transparency](5-literature.qmd)

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  20   | 3/26   | Basics of Information Disclosure      | [{{< fa magnifying-glass >}}](/schedule/5-0.html)        |
|       |        | **Research Proposal 3 Due**           | [{{< fa pen  >}}](/assignments/research-proposals.html)  |
|  21   | 3/31   | Physician Quality                     | [{{< fa magnifying-glass >}}](/schedule/5-1.html)        |
|  22   | 4/2    | Insurance Ratings                     | [{{< fa magnifying-glass >}}](/schedule/5-2.html)        |
|  23   | 4/7    | Price Transparency                    | [{{< fa magnifying-glass >}}](/schedule/5-3.html)        |
: {tbl-colwidths="\[10,15,35,20\]"}


## Module 6: Recent Job Market Papers

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  24   | 4/9    | JMPs from 2023                        | [{{< fa magnifying-glass >}}](/schedule/6-1.html)         |
|  25   | 4/14   | JMPs from 2024                        | [{{< fa magnifying-glass >}}](/schedule/6-2.html)         |
|  26   | 4/16   | JMPs from 2025                        | [{{< fa magnifying-glass >}}](/schedule/6-3.html)         |
: {tbl-colwidths="\[10,15,35,20\]"}


## Final Research Plans

| Class | Dates  | Topic                                 | Description |
|:-----:|--------|---------------------------------------|:-----------:|
|  27   | 4/21   | **Research Plans**                     | [{{< fa pen  >}}](/assignments/research-plans.html)      |
|  28   | 4/23   | **Research Plans**                     | [{{< fa pen  >}}](/assignments/research-plans.html)      |
|       |        | **Empirical Exercise Due**             | [{{< fa pen  >}}](/assignments/empirical-exercises.html) |
: {tbl-colwidths="\[10,15,35,20\]"}
