---
title: "Empirical Exercises"
# format:
#   pdf: default
---

You must choose one of four empirical exercises to complete this semester. The exercises are listed and described in more detail below (or on our class website):

- [Exercise 1: Difference-in-differences](exercise1.qmd)
- [Exercise 2: Instrumental variables](exercise2.qmd)
- [Exercise 3: Regression Discontinuity](exercise3.qmd)
- [Exercise 4: Hospital markets + demand estimation](exercise4.qmd)

Please note which exercise you plan to complete on our shared Google Sheet by **January 29** and submit your final assignment as a GitHub repository link by **April 23**. The exercise is worth 20 points toward your final grade, 2 points for each of 10 questions. 

In your repository, please include a final PDF file, along with all of your supporting documentation, including your code files (Stata, R, Python, SAS, etc.), all figures/tables, and some instructions (e.g., as part of your ReadMe file) that introduce the reader to your data and the sequence in which your code should be run. Practice writing good code and showing me only what I would need to recreate your results. Please also be sure to organize your folders in a useful way (e.g., clearly organized subdirectories such as "data", "data-code", "analysis", "results", etc.). It's good to start developing some organization practices that work best for you as early as possible. It's extremely easy to forget what you were doing on a project once you have several things going at once, especially when you wait for 6-8 months after submitting a paper for publication. The last thing you want is to not be able to replicate your own work!


